### ISSUE TITLE
Mudanças - Index

### ISSUE THREAD

**Issue by BRZangado** [Anasps/Site-Faculdade#56]
## Descrição
Algumas alterações foram requisitadas pelo PO, envolvendo atualização de nomenclatura e realocação da sessão de cursos online(cursos de capacitação) dentro da sessão ensino à distância.

## Tarefas
* Mudança do background
* Renomear botão de cursos online para "Pesquisa e extensão"
  * Redirecionar conteúdo para sessão Nupress

**Comment by FLP2** [comment]
Background alterado.
